package bddTraders;

public record Client(String firstName, String lastName, String email, int id) {
    public Client (String firstName, String lastName, String email) {
        this(firstName, lastName, email, 0);
    }
}
/*
When you declare a class using record in Java,
the accessors (getters) are automatically generated behind the scenes.
The getters generated by record can be accessed by field names.

        Client newClient = new Client("michael", "white", "blue@gmail.com");
        newClient.firstName();

However, records are designed as immutable (unchangeable) data structures in Java,
and therefore, they do not generate setter methods.
That is, after creating a record object, you cannot update its fields.
Instead, you should create a new record object.
To overcome this situation or the immutability feature of record,
you can use a traditional POJO (Plain Old Java Object) instead of record
 */
